In [1]:
pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np  # Import numpy library

In [8]:
print(np.zeros(10, int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
arr = np.arange(100)
print(arr)
print(arr.shape)
c = arr.reshape(5,5, -1)    # -1 의미하는건 알아서 계산해라 (-1 means calculate automatically)
print(c)
print(c.shape)
print(c.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]
(5, 5, 4)
3


In [27]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.ndim)
print(a.shape)
b = a.reshape(4, 3)
print(b)
print(b.ndim)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [ ]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(data) * 2
print(arr)      # 각 변수에 2를 곱함

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[1, :])
print(a[:, 1])
print(a[1, 1:])
print(a[:, :2])

[4]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [45]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(
    2 * a + b,
    a == 2,
    b > 10,
    (a == 2) & (b > 10)
)

[12 24 36] [False  True False] [False  True  True] [False  True False]


In [56]:
a = np.array(range(1, 13)).reshape(3, -1)
a[:, [0, 3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [59]:
a = np.array(range(1, 13)).reshape(3, -1)
a[::-1, :]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [65]:
x = np.array(range(1, 21)).reshape(2, -1)

# 3의 배수
print(x[x % 3 == 0])

# 4의 배수 + 1
print(x[x % 4 == 1])

# 3의 배수 & 4의 배수 + 1
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
